name: Deploy to Amazon ECS

on:
  workflow_call:

env:
  ECR_REPOSITORY: who-am-i
  ECS_SERVICE: who-am-i
  ECS_CLUSTER: who-am-i
  ECS_TASK_DEFINITION: .aws/task-definition.json
  CONTAINER_NAME: who-am-i

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::381492151940:role/who-am-i
          role-session-name: who_am_i
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT | 
          aws ecs update-service --cluster who-am-i --service who-am-i --force-new-deployment --region us-east-1