name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "**" ]

  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

  call-validation:
    uses: ./.github/workflows/validation-ci.yml

  call-deployment:
    needs: call-validation
    uses: ./.github/workflows/deployment-ci.yml